# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='text',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
