# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_auto_20160619_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='memory',
            options={'verbose_name_plural': 'memories'},
        ),
        migrations.AddField(
            model_name='memory',
            name='day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='location',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='memory',
            unique_together=set([('prompt', 'title', 'creator')]),
        ),
    ]
